apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: fint-flyt-egrunnerverv-okonomi
    namespace: fintlabs-no
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: fint-flyt-egrunnerverv-okonomi
    minReplicas: 1
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 90
